### ISSUE TITLE
PathwayMultiOrganismRule is to be fine-tuned

### ISSUE THREAD

**Issue by IgorRodchenkov** [BioPAX/validator#9]
For example, @gbader found the following example -
```
  • ERROR: multi.organism.pathway , category: RECOMMENDATION, cases: 1, not fixed: 1
Components have different values for the 'organism' property. Check that this is a valid multi-organism interaction
    • object: http://identifiers.org/smpdb/SMP00575
pathway has: Species/1, components have: BiologicalState/49; BiologicalState/8; BiologicalState/18; BiologicalState/3; (found by: org.biopax.validator.rules.PathwayMultiOrganismRule)
```
which is probably not an error - as all the organisms are (_supposedly_ -IR) the same, they just use different BioSource instances (_equivalent?_ -IR).

**Comment by gbader** [comment]
Hi - the problem is when you want to specify different cell types in the same organism - unfortunately you need to use different biosources (that is a design flaw in biopax).
